version: 0.0
os: linux
files:
  - source: /config.ru
    destination: /home/ec2-user/ruby-sinatra
  - source: /Gemfile
    destination: /home/ec2-user/ruby-sinatra
  - source: /server.rb
    destination: /home/ec2-user/ruby-sinatra
  - source: /scripts/requirements.txt
    destination: /home/ec2-user/scripts
hooks:
  AfterInstall:
    - location: scripts/install_python3
      timeout: 300
      runas: root
    - location: scripts/codestar_remote_access
      timeout: 300
      runas: root
    - location: scripts/install_ruby
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
